# Issues flagged for future exploration {#future_explore}

This section documents issues that we decided to flag for future consideration, perhaps when more data are available.

## Age distribution
We decided to weight the sample to match the age distribution reported for males in the census. The issue is that this may not correspond to the age distribution of MSM, particularly if there is differential migration for MSM and non-MSM. We could eventually try to tackle this, perhaps using Susie Cassel's data on migration patterns from the Mobile study. We could represent internal migration as changes in the regional attribute by age. However, incorporating this would require weighting the sample to the joint distriubtion of age and region, which stretch the current data quite thin. 

## Age mixing by age
Section \@ref(explore_heterogeneity) documents that parameterizing age mixing as the absolute difference in the square root of ego and alter ages does not fully acount for heterogeneity in age mixing by the age of the partners. Even after taking the difference in the cube root of ego and alter ages, age differences are greater for older egos. Further research is needed to identify ways to paramterize age mixing to remove heterogeneity by age.

There are some ages for which no egos reported on most recent ongoing persistent or instantaneous partnerships, though men at these ages did report ongoing persistent or instantaneous partnerships. For the way we are calculating the target statistic for the absolute difference in the square root of ego and alter ages (section \@ref(age_mixing)), the partnerships for men at these ages are omitted. Consider trying to interpolate the row conditional probabilities for age mixing for men at these ages using the averages from the two nearest ages with non-missing data on the most recent partner ages.

## Network boundary specification
We decided to exclude data on most recent partners outside of the modeled age range (18-59), but we are keeping the egos who reported these partners in the network and including their out-of-range partners in calculation of momentary degree. In exploratory analyses, we observed that, compared to men who reported on partners in the age range, men whose most recent partners were outside of the modeled age range were more likely to be Hispanic and less likely to be "Other" race/ethnicity, more likely to have a main partner, reported lower coital frequency with main partners, and  were more likely to be bottoms and less likely to be versatile. Future work could explore the impact of dropping these men and/or consider including their out-of-range partnerships using a heat bath approach.

## Race mixing
We decided to collapse the off-diagonal elements and represent race mixing with a nodematch term due to small numbers by partner type. We also decided to collapse the persistent and instantaneous partnership networks in looking at race mixing due to the small numbers in some cells. With more data, future modeling work should represent these networks separately and use nodemix terms, as analyses indicated that the off-diagonal $\alpha_{ij}$ terms are heterogeneous (see section \@ref(mixing)).

## Regional mixing
Exploratory analyses indicate that several parameters vary by region, but we lack data on regional mixing. To inform mixing matrices by region, future data collection should include questions about patterns of regional mixing for each partnership type (i.e. ask where alters live).

## Partnership duration
Current methods require an assumption that the durations of main and persistent partnerships follow an exponential distribution. Further work is needed to identify ways to specify duration without relying on this assumption. Additionally, more work is needed to explore how best to specify partnership duration in a network with a specific age structure and to capture heterogeneity in partnership duration by the age of the partners.

## Sex role by age
In section \@ref(explore_heterogeneity), we observed that sex role varies by age. Plot \@ref(fig:plots_explore_sexrole) show some heterogeneity by age, but the effects are fairly modest. We decided not to stratify sex role by age in the model for this reason and because capturing heterogeneity in sex role by age is difficult; sex role influences the network model, such that this would introduce complexity in ensuring balance in age mixing. With more data and time to code and debug the model, this could be further explored.

## Condom use typologies
The plots of condom use probabilites (\@ref(fig:plotsexplore_condoms_main), \@ref(fig:plotsexplore_condoms_pers), \@ref(fig:plotsexplore_condoms_inst)) suggest that there are three typologies of condom user: never, sometimes, and always. Defining a parameter for condom use based on the observed mean level of condom use doesn't capture this patterning whereby some men always use condoms and others never do. But the data collected in the WHPP survey are not ideal to define what these individual-level typologies are because we only measured condom use at the dyad level with the most recent partner. This makes it difficult to disentangle individual propensities from reported condom use in a given dyad, which is a reflection of the propensities of both partners. 
  Future work, preferably with better data, could seek to define individual propensities and rules to decide what happens when two individuals with different propensities mix. We could assign men to one of three typologies for each partner type: never, sometimes, or always condom users. If we had the right data, we could also make this more complex and define patterns of condom use across partner types (e.g. never with main partner, sometimes with persistent, never with one-time). We would need to specify offsets in the formation models to prevent a never-user from mixing with an always-user. For never-sometimes and always-sometimes dyads, we could say that the preferences of the never- or always- users trump those of the never user. If two sometimes-users mix, we would need to determine what the probability of condom use would be. The specified distribution of men in these categories and the rules for dyad-level condom use would need to preserve the observed mean probability of condom use by partner type.

## PrEP use by race and region interaction
With more data, consider exploring whether PrEP uptake differs by the interaction of race/ethnicity and region.

## Behaviors in the absence of PrEP
A challenge with using data from the WHPP survey to estimate behavioral parameters is that ~20% of the sample is using PrEP, and some behaviors may have changed with the use of PrEP, such as condom use and possibly things like coital freuqency, sex role, and the number of partners. So including these men in estimating parameter values may yield over- or under-estimates, but PrEP users may have been different on these parameters before starting PrEP. 

One option for how to handle this is to fit a model conditional on a set of covariates and not being a recent PrEP user and then use this model to predict the parameter for PrEP users had they not been on PrEP. We would then combine the observed data from PrEP non-users with the predicted data from PrEP users to obtain our estimates. Covariates for these models would need to be carefully selected to try to adjust for confounders that might explain differences between PrEP users and non-users while avoiding variables that also may have changed with PrEP use. 

Another option is to use data from other sources (secondary datasets from before PrEP was scaled up or published longitudinal studies) to estimate either what the behaviors would be in the absence of PrEP or estimate what the change in the behavior is with PrEP use. These external estimates could be used in combination with the approach above to see whether model predictions align with other estimates.

In addition to sexual behaviors that might be shaped by risk compensation, HIV testing patterns change with PrEP use. In estimating interest intervals, we will not want to include data from PrEP users, but it is possible that men who have taken PrEP were more likely to test before initiating. We could use the prediction approach above to impute testing intervals for PrEP users from PrEP non-users who are of similar demographic and risk profiles. A limitation of this approach is that it is possible that the factor that explains why men on PrEP have initated PrEP and their similarly-indicated counterparts have not is that men who have initated PrEP were more likely to test, so it may not be possible to obtain "exchangeable" groups.
