# Notes on PrEP use

<span style="color:red">This section describes the findings from the WHPP survey on the proportion of men who meet [Washington State guidelines](http://www.kingcounty.gov/healthservices/health/communicable/~/media/health/publichealth/documents/hiv/PrEP-Implementation-Guidelines.ashx).^[In the WHPP survey, any diagnosis of syphilis was considered an indication for recommending PrEP, regardless of the stage of infection. We classified respondents in the "discuss PrEP" candidacy category if they did not meet the criteria for recommending PrEP and reported any of the following in the prior 12 months: condomless anal sex (CAS) with a partner not considered to be main or primary, CAS with a partner of unknown or positive HIV status, diagnosis of urethral gonorrhea or rectal chlamydia, or use of non-prescription injection drugs. Men also fit into this category if they reported any ongoing partnerships with HIV-positive persons who had been on ART for more than 6 months and were virologically suppressed. We did not measure whether men reported HIV-positive female partners with whom they are trying to become pregnant, completion of a course of post-exposure prophylaxis for non-occupational exposure, or seeking a prescription for PrEP.] for PrEP use, the proportion who report use of PrEP, and correlates with use of PrEP.</span>