# Overview {#overview}

This document presents the results of data analyses for estimation of parameters for the Washington HIV Model for MSM and records the assumptions made in that process. The document is organized into the following sections:

* Model parameters and functions
* Network composition (Demographics)
* Degree and concurrency
* Rate of instantaneous partnerships
* Duration
* Age mixing
* Race mixing
* Regional mixing
* One-time network
* Summary of decisions made
* Issues for future exploration
* References
* Appendices:
    * Notes on the demographic composition of the Washington HIV Prevention Project sample
    * Reweighting data from the Washington HIV Prevention Project internet survey
    * Model structure: heterogeneity on nodal attributes
    * Notes on sexual mixing
    * Notes on the rate of instantaneous (one-time) partnerships
    * Notes on condom use and coital frequency
    * Notes on limitations to using data from the most recent partner only
    * Notes on restricting alters to the modeled age range
    * Notes on HIV testing
    * Notes on PrEP eligiblity and use
