---
output:
  html_document:
    toc: true
    toc_float: true
---
# Main network model diagnostics - unbalanced
This file shows diagnostics for the main network model fit using unbalanced racial/ethnic mixing matrices and degree terms based on reported data.

## Load packages and model fits
```{r, warning=FALSE}
rm(list = ls())
suppressMessages(library("EpiModelHIV"))
library("latticeExtra")

load(file = "/homes/dpwhite/R/GitHub Repos/WHAMP/Model fits and simulations/est/fit.m.unbalanced.whamp.rda")

options(tibble.print_max = 10000)
```

## Model terms and control settings
```{r, echo=FALSE}
(targets <- cbind.data.frame("Terms" = c(fit.m$target.stats.names, "degrange", "nodematch.role.class.I", "nodematch.role.class.R", "mix.region.EW.KC", "mix.region.EW.OW", "mix.region.KC.OW"), "Stats" = c(fit.m$target.stats, -Inf, -Inf, -Inf, -Inf, -Inf)))
```

The control settings are:
```{r, eval=FALSE}
set.control.ergm = control.ergm(MCMC.interval = 1e+5,
                                MCMC.samplesize = 7500,
                                MCMC.burnin = 1e+6,
                                MPLE.max.dyad.types = 1e+7,
                                init.method = "zeros",
                                MCMLE.maxit = 400,
                                parallel = np/2, 
                                parallel.type="PSOCK"))
```

## MCMC diagnostics

```{r, message=FALSE, echo=FALSE}
mcmc.diagnostics(fit.m$fit)
```

## Summary of model fit

```{r}
summary(fit.m)
```

## Network diagnostics

```{r}
(dx_main <- netdx(fit.m, nsims = 10, nsteps = 1000, ncores = 4))
plot(dx_main, type="formation")
plot(dx_main, type="duration")
plot(dx_main, type="dissolution")
```
